on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: Continuous Integration

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install
      - name: Checking Prettier
        run: yarn lint
  build:
    name: Run Tests
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install
      - name: Run tests
        uses: GabrielBB/xvfb-action@v1.4
        with:
          run: yarn test --silent
